# Generated by Django 5.2.1 on 2025-05-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='description',
            new_name='date',
        ),
    ]
